#DROP TABLE IF EXISTS link_pages;
CREATE TABLE IF NOT EXISTS link_pages (
	id INTEGER UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	site_id INTEGER UNSIGNED,
	title VARCHAR(128),

	introduction TEXT,

	created DATETIME,
	modified DATETIME
);

#DROP TABLE IF EXISTS links;
CREATE TABLE IF NOT EXISTS links (
	id INTEGER UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	site_id INTEGER UNSIGNED,
	user_id INTEGER UNSIGNED,
	link_category_id INTEGER UNSIGNED,
	url VARCHAR(255),
	title VARCHAR(128),
	description TEXT,
	ix INTEGER UNSIGNED,

	created DATETIME,
	modified DATETIME
);

#DROP TABLE IF EXISTS link_categories;
CREATE TABLE IF NOT EXISTS link_categories (
	id INTEGER UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	site_id INTEGER UNSIGNED,
	user_id INTEGER UNSIGNED,
	title VARCHAR(128),
	ix INTEGER UNSIGNED,

	created DATETIME,
	modified DATETIME
);
